version: 0.2  
  
phases:  
  pre_build:  
    commands:  
      - echo Logging in to AWS ECR...  
      - aws ecr get-login-password --region <YOUR_REGION> | docker login --username AWS --password-stdin <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.<YOUR_REGION>.amazonaws.com  
  build:  
    commands:  
      - echo Building Docker image...  
      - docker build -t <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.<YOUR_REGION>.amazonaws.com/<YOUR_ECR_REPOSITORY_NAME> .  
      - echo Pushing Docker image to AWS ECR...  
      - docker push <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.<YOUR_REGION>.amazonaws.com/<YOUR_ECR_REPOSITORY_NAME>  
